[package]
name = "eden-mod-manager"
version = "0.4.2"
description = "Instalador de mods e compressor NSZ para Eden, yuzu e Ryujinx"
authors = ["pendiego"]
license = "MIT"
repository = "https://github.com/pendiego/Eden-Mod-Manager"
edition = "2021"

[lib]
name = "eden_mod_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "gzip"] }
tokio = { version = "1", features = ["sync", "time"] }
zip = { version = "8", default-features = false, features = ["deflate"] }
sevenz-rust2 = "0.23"
unrar = "0.5"
regex = "1"
dirs = "7"
walkdir = "2"
parking_lot = "0.12"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
tauri-plugin-updater = "2"
minisign-verify = "0.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
